"""purchase model

Revision ID: 8f08650a7df8
Revises: f0dc6d6eeba6
Create Date: 2024-02-20 21:19:41.119978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f08650a7df8'
down_revision: Union[str, None] = 'f0dc6d6eeba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('price', mysql.FLOAT(precision=2), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'finished', name='statustype'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcement.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_id'), 'purchase', ['id'], unique=False)
    op.alter_column('announcement', 'price',
               existing_type=sa.REAL(),
               type_=mysql.FLOAT(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcement', 'price',
               existing_type=mysql.FLOAT(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_purchase_id'), table_name='purchase')
    op.drop_table('purchase')
    # ### end Alembic commands ###
