"""image_model

Revision ID: 9a15333bbee4
Revises: 8443d5349e2b
Create Date: 2024-02-28 10:44:55.602217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a15333bbee4'
down_revision: Union[str, None] = '8443d5349e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.alter_column('announcement', 'price',
               existing_type=sa.REAL(),
               type_=mysql.FLOAT(precision=2),
               existing_nullable=True)
    op.alter_column('purchase', 'price',
               existing_type=sa.REAL(),
               type_=mysql.FLOAT(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase', 'price',
               existing_type=mysql.FLOAT(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('announcement', 'price',
               existing_type=mysql.FLOAT(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
