"""new_token_model

Revision ID: 9ae2d53a19bb
Revises: d473e4dfca87
Create Date: 2024-02-25 20:13:55.385240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae2d53a19bb'
down_revision: Union[str, None] = 'd473e4dfca87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_id', table_name='token')
    op.create_foreign_key(None, 'token', 'user', ['user_id'], ['id'])
    op.drop_column('token', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.create_index('ix_token_id', 'token', ['id'], unique=False)
    # ### end Alembic commands ###
